// Bluey Alpha 45 — Room Intelligence V1
// Makes Bluey conversationally aware of the room and its interactive objects.
(function(){
'use strict';
const WS=()=>window.BlueyWorldStandard;
const ROOM_INTEL={
 workshop:{purpose:'turn an idea into something we can inspect, sketch, or test',suggestions:[['idea','plan','figure','design','build'],['workshop-blueprint','The sketch board might help. We can get the idea out of your head and give it some shape.'],['test','prototype','try'],['workshop-prototype','This sounds like prototype territory. We can make a small version and learn from it.'],['stuck','problem','fix'],['workshop-bench','Let’s put it on the workbench and break it into smaller pieces.']]},
 observatory:{purpose:'explore questions, patterns, and things worth looking at more closely',suggestions:[['explore','look','see','space','star'],['observatory-telescope','Telescope moment. 🔭 Want to pick something far away and take a closer look?'],['pattern','map','connect'],['observatory-starmap','The star map feels right for this one. Let’s see what connects to what.'],['earth','world','perspective'],['observatory-earth','Come look at Earth with me. Sometimes backing way up changes the question.']]},
 garage:{purpose:'tinker with practical problems and useful tools',suggestions:[['tool','fix','repair','make'],['garage-tools','Toolbox time. 🧰 Let’s figure out what kind of problem we’re actually fixing.'],['mystery','unknown','curious'],['garage-box','Hmm. Mystery-box energy. Want to open the problem and see what’s actually inside?']]},
 arcade:{purpose:'learn through attempts, feedback, play, and trying again',suggestions:[['practice','learn','try','again','score'],['arcade-cabinet','This feels like an arcade problem: try it, see what happens, adjust, try again.'],['win','goal','progress'],['arcade-prize','Let’s define what “winning” looks like before we chase the trophy. 🏆']]},
 beach:{purpose:'slow down, notice things, and explore with curiosity',suggestions:[['idea','think','stuck','relax'],['beach-shell','Let’s borrow the seashell for a second. 🐚 What’s the smallest interesting piece of this?'],['build','temporary','experiment'],['beach-castle','Sandcastle rule: we’re allowed to build a version that doesn’t have to last forever.']]},
 forest:{purpose:'notice hidden systems, connections, and gradual growth',suggestions:[['connect','system','network','hidden'],['forest-mushroom','This might be a mycelium problem — lots of the important stuff could be happening underneath what we can see.'],['grow','time','progress'],['forest-tree','Tree logic: small growth still counts. What’s one branch we can grow next?']]},
 museum:{purpose:'learn from examples, history, artifacts, and different interpretations',suggestions:[['history','before','old','example'],['museum-fossil','Let’s use the fossil approach: what evidence did the earlier version leave behind?'],['interpret','view','meaning','creative'],['museum-art','Painting question: is there another way to look at this?']]},
 aquarium:{purpose:'observe behavior, movement, and systems from another perspective',suggestions:[['flow','move','process','behavior'],['aquarium-fish','Let’s watch the flow instead of one moment. Where does this start, move, and end?'],['complex','ecosystem','many'],['aquarium-coral','Coral-reef problem: lots of small parts may be supporting the whole thing.']]}
};
function room(){return WS()?.current?.()||'home'}
function objectById(id){return WS()?.rooms?.[room()]?.objects?.find(o=>o.id===id)}
function markObject(id){const S=WS()?.stage?.();if(!S)return;const cards=[...S.querySelectorAll('.bluey-interactive-object,.bluey-trip-object,.bluey-object')];const cfg=WS()?.rooms?.[room()]?.objects||[];const idx=cfg.findIndex(o=>o.id===id);const el=cards[idx];if(!el)return;el.classList.add('bluey-room-suggested');setTimeout(()=>el.classList.remove('bluey-room-suggested'),4200)}
function suggestion(text){const intel=ROOM_INTEL[room()];if(!intel)return null;const q=text.toLowerCase();for(let i=0;i<intel.suggestions.length;i+=2){const words=intel.suggestions[i],data=intel.suggestions[i+1];if(words.some(w=>q.includes(w)))return {objectId:data[0],response:data[1]}}return null}
function ambient(){const r=room(),intel=ROOM_INTEL[r];if(!intel)return null;const objs=WS()?.rooms?.[r]?.objects||[];if(!objs.length)return null;const o=objs[Math.floor(Math.random()*objs.length)];const lines=[`You know what? The ${o.title.toLowerCase()} might actually be useful here.`,`I just glanced at the ${o.title.toLowerCase()}. That may be a clue.`,`This room is giving me an idea. The ${o.title.toLowerCase()} could help us think about this differently.`];return {objectId:o.id,response:lines[Math.floor(Math.random()*lines.length)]}}
function roomHelp(){const r=room(),intel=ROOM_INTEL[r];if(!intel)return null;const objs=WS()?.rooms?.[r]?.objects||[];return `We’re in the ${r}. This is a good place to ${intel.purpose}. ${objs.length?`We’ve got ${objs.map(o=>o.title).join(', ')} around us.`:''}`}
const previousSend=window.send;window.send=async function(t){const c=String(t||'').trim();if(!c)return;const l=c.toLowerCase();if(/\b(what can we do here|what do we do here|why are we here|what is this room for|what's this room for)\b/.test(l)){add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';const a=roomHelp();if(a){setTimeout(()=>{add('assistant',a);history.push({role:'assistant',content:a});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(a,'curious')},180);return}}
const s=suggestion(c);if(s&&!/\b(go|take|show|visit|travel|room|office)\b/.test(l)){add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';markObject(s.objectId);setTimeout(()=>{add('assistant',s.response);history.push({role:'assistant',content:s.response});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(s.response,'curious')},180);return}
return previousSend(c)};
const css=document.createElement('style');css.textContent=`.bluey-room-suggested{animation:blueyRoomNudge 1.15s ease-in-out 3!important;box-shadow:0 0 0 4px rgba(28,174,232,.22),0 8px 28px rgba(15,126,180,.25)!important}@keyframes blueyRoomNudge{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-7px) scale(1.04)}}@media(prefers-reduced-motion:reduce){.bluey-room-suggested{animation:none!important;outline:4px solid rgba(28,174,232,.3)}}`;document.head.appendChild(css);
window.BlueyRoomIntelligence={version:'1.0',rooms:ROOM_INTEL,suggestion,ambient,roomHelp,markObject};
console.info('[Bluey] Alpha 45 Room Intelligence V1 ready');
})();