// Bluey Alpha 42 — Object Continuity V1.1
// Objects remain part of Bluey's world after their stage UI is tucked away.
(function(){
'use strict';
if(window.BlueyCharacter)window.BlueyCharacter.version='1.0-alpha42';
if(window.blueyAbout)window.blueyAbout.version='1.0-alpha42';
let recentObject=null,recentObjectAt=0;
const aliases={'home-mat':['welcome mat','doormat','door mat','mat'],'home-lamp':['idea lamp','lamp','light'],'home-marbles':['marble jar','marbles','marble'],'quiet-leaf':['leaf','quiet leaf'],'quiet-hourglass':['hourglass','sand timer','timer'],'edge-light':['edge light','little light'],'edge-marker':['edge marker','marker']};
function roomObjects(){return Object.values(window.BLUEY_OBJECTS||{}).flat()}
function findObject(id){return roomObjects().find(o=>o&&o.id===id)||null}
const hasWord42=((s,w)=>new RegExp('(^|[^a-z0-9])'+String(w).toLowerCase().replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(s|es)?($|[^a-z0-9])','i').test(s));function resolveObject(text){const q=String(text||'').toLowerCase();for(const[id,names]of Object.entries(aliases))if(names.some(n=>hasWord42(q,n)))return findObject(id)||{id,title:names[0]};const direct=roomObjects().find(o=>[o.title,...(o.names||[])].filter(Boolean).some(n=>hasWord42(q,n)));if(direct)return direct;if(/\b(it|that|this|thing|object|favorite)\b/i.test(q)&&recentObject&&Date.now()-recentObjectAt<30*60*1000)return recentObject;const favorite=window.BlueyRelationshipMemory?.favoriteObject?.();if(/\b(favorite|favourite)\b/i.test(q)&&favorite)return findObject(favorite.key)||{id:favorite.key,title:favorite.name};return null}
function rememberRecent(obj){if(!obj)return;recentObject=obj;recentObjectAt=Date.now();try{sessionStorage.setItem('bluey.recentObject.v1',JSON.stringify({id:obj.id,at:recentObjectAt}))}catch(_){}}
try{const saved=JSON.parse(sessionStorage.getItem('bluey.recentObject.v1')||'null');if(saved&&saved.id){recentObject=findObject(saved.id)||{id:saved.id,title:saved.id};recentObjectAt=saved.at||Date.now()}}catch(_){}
function displayName(obj){return obj?.title||aliases[obj?.id]?.[0]||'that object'}
function tuckedReply(obj){const name=displayName(obj);const memory=window.BlueyRelationshipMemory?.summary?.();const achieved=(memory?.achievements||[]).some(a=>/welcome mat/i.test(a))&&obj.id==='home-mat';if(achieved)return `Oh, the welcome mat? I tucked it away so it wouldn’t sit on top of our conversation. Don’t worry — my Welcome Mat Enthusiast hasn’t lost it. 😄`;const options=[`Oh, ${name}? I tucked it away so the stage wouldn’t get in the way of our conversation. It’s still here.`,`${name} is still part of the room. I just cleared the stage after we finished poking at it.`,`I didn’t lose ${name}. 😄 I tucked it away to give our conversation some room.`];return options[Math.floor(Math.random()*options.length)]}
const roomMap={'home-mat':'home','home-lamp':'home','home-marbles':'home','quiet-leaf':'quiet','quiet-hourglass':'quiet','edge-light':'edge','edge-marker':'edge'};
function restoreObject(obj){const room=roomMap[obj.id];if(!room)return false;if(window.blueyWorld!==room&&typeof enterWorld==='function')enterWorld(room,false);if(typeof clearInteractiveObjects==='function')clearInteractiveObjects();const fresh=findObject(obj.id)||obj;if(typeof createBlueyObject!=='function'||!window.blueyStage37)return false;const node=createBlueyObject(fresh);blueyStage37.appendChild(node);if(Array.isArray(window.blueyVisibleObjects)&&!blueyVisibleObjects.includes(node))blueyVisibleObjects.push(node);if(window.BlueyMobileStage?.explore)window.BlueyMobileStage.explore();return true}
function isWhere(q){return /\b(where|what happened|what'd happen|where'd|where did)\b/i.test(q)&&/\b(go|gone|happen|is|are|did)\b/i.test(q)}
function isRestore(q){return /\b(bring|show|put|restore|get)\b/i.test(q)&&/\b(back|again|stage|here|it|that|mat|lamp|marble|leaf|hourglass|marker|light)\b/i.test(q)}
function say(answer){add('assistant',answer);history.push({role:'assistant',content:answer});behavior('curious');if(typeof blueyVoiceOn==='undefined'||blueyVoiceOn)speak(answer,'curious')}
const inspectBefore42=window.inspectBlueyObject;if(typeof inspectBefore42==='function')window.inspectBlueyObject=function(obj,el){rememberRecent(obj);return inspectBefore42(obj,el)};
const sendBefore42=window.send;
window.send=async function(text){const q=String(text||'').trim();const obj=resolveObject(q);if(obj&&(isWhere(q)||isRestore(q))){add('user',q);history.push({role:'user',content:q});if(window.input)input.value='';rememberRecent(obj);if(isRestore(q)){const restored=restoreObject(obj);const answer=restored?`There you go — ${displayName(obj)} is back. Just that one. I had a feeling you weren’t finished with it. 😄`:`I remember ${displayName(obj)}. It isn’t on this stage right now, but it’s still part of my world.`;setTimeout(()=>say(answer),180);return}setTimeout(()=>say(tuckedReply(obj)),180);return}return sendBefore42(q)};
window.BlueyObjectContinuity={version:'1.1',recent:()=>recentObject,resolve:resolveObject,restore:id=>{const obj=findObject(id)||{id,title:id};rememberRecent(obj);return restoreObject(obj)}};
console.info('[Bluey] Alpha 42 Object Continuity V1.1 ready');
})();