// Alpha 40 — every room and short travel stop has tappable stage details.
// Alpha 47 production baseline: Alpha 40 is the stable bootstrap that loads 41–46.
window.BLUEY_RUNTIME_VERSION='1.0 Alpha 47';
if(window.BlueyCharacter)window.BlueyCharacter.version='1.0-alpha47';
if(window.blueyAbout)window.blueyAbout.version='1.0-alpha47';
(function(){const badge=document.getElementById('bluey-version');if(badge)badge.textContent=window.BLUEY_RUNTIME_VERSION;document.title=window.BLUEY_RUNTIME_VERSION;})();

BLUEY_OBJECTS.home=[
 {id:'home-marbles',icon:'🔮',names:['marble','marbles','marble jar'],title:'Bluey’s marble jar',short:'My marble jar. They are colorful, perfectly round, and I feel a little represented.',deeper:'I started collecting them because they look like tiny versions of me. Each one has its own colors and swirls.',rabbit:'Want to pick a marble and invent a story for it?'},
 {id:'home-lamp',icon:'💡',names:['lamp','light','idea lamp'],title:'The idea lamp',short:'My little idea lamp. It comes on when a question gets interesting. It has been busy lately.',deeper:'A useful idea often starts as a small hunch. We can test it, adjust it, and see if it helps.',rabbit:'Got a question you want to shine a light on?'},
 {id:'home-mat',icon:'⌂',names:['welcome mat','door mat','mat'],title:'Welcome mat',short:'A welcome mat for visitors. It says “come on in” without making anybody ring a tiny digital doorbell.',deeper:'This is my home base. I can wander off to another room and still zip back here in a blink.',rabbit:'Want to see another room?'}
];
BLUEY_OBJECTS.quiet=[{id:'quiet-leaf',icon:'🍃',names:['leaf','quiet leaf'],title:'The slow-falling leaf',short:'This leaf takes its time getting to the ground. I like that it is not in a hurry to finish.',deeper:'Taking a pause can make it easier to notice what matters before choosing a next step.',rabbit:'Want a quiet minute, or should we follow the next question?'},{id:'quiet-hourglass',icon:'⌛',names:['hourglass','sand timer','timer'],title:'Little sand timer',short:'A little sand timer. It reminds me that a short pause can be useful without needing to solve anything.',deeper:'Breaking a task into a small next step can make it feel less tangled.',rabbit:'Tell me what feels tangled and we can find one first step.'}];
BLUEY_OBJECTS.edge=[{id:'edge-light',icon:'✦',names:['light','edge light','glow'],title:'The tiny edge light',short:'That tiny light is as far as I have explored so far. I am curious about it, but I do not have to rush past it.',deeper:'Sometimes it helps to name what we know, what we do not know yet, and what we could safely check next.',rabbit:'What would you want to find if we explored a little farther?'},{id:'edge-marker',icon:'⋮',names:['marker','sign','edge marker'],title:'The Edge marker',short:'My little marker says “this is where I stopped.” It is more honest than pretending I have seen everything.',deeper:'A clear boundary can be useful: it tells us what is known and where a new question begins.',rabbit:'We can explore the next question together, one small step at a time.'}];
const blueyRenderRoomObjectsBefore40=renderInteractiveObjects;renderInteractiveObjects=function(place){const result=blueyRenderRoomObjectsBefore40(place);blueyVisibleObjects.forEach(object=>blueyStage37.appendChild(object));return result};renderInteractiveObjects(blueyWorld||'home');
const blueyObjectTapCounts40=new Map(),blueyObjectOpeners40=['Oh, this one.','You found one of my little things.','Ha — good pick.','I wondered if you would tap that.','This one has a story.','Ooh, you noticed it.'],blueyObjectClosers40=['',' There’s a little more to this one if you’re curious.',' That one makes me smile, in the very digital sense.',' You can ask me anything about it.',' We can follow that rabbit hole if you want.'],blueyReturnLines40=['You came back to it.','Back again — I like your curiosity.','Okay, this one definitely has your attention.','We meet again.'];
const blueyObjectPlay40={'home-marbles':['Another marble inspection? Excellent choice.','At this point I should probably let you name one.','You definitely have a favorite object in my house, don’t you?','Okay, pick a color. I’m emotionally prepared to adopt a marble.','I think you’re testing whether I can run out of marble opinions. I cannot. 😄'],'home-lamp':['You keep coming back to this lamp. I think you have an idea brewing.','Careful. Keep tapping it and we might accidentally invent something.','Okay, now I’m curious. What are you thinking about?','The lamp says you’re up to something. I’m inclined to believe it.','One more tap and I’m calling this an official brainstorm. 😄'],'home-mat':['Okay, you really like this welcome mat. 😄','Yep. Still a welcome mat. I checked.','I’m starting to think this is your favorite thing in my house.','Tap it again and I’m charging admission. 😂','All right, you win. The welcome mat likes you too.']};
const blueyGenericPlay40=['Okay, you definitely noticed this one. 😄','I think you’re testing me now.','We’ve officially moved from inspecting this to hanging out with it.','Yep. Still here. Still interesting.','At this point, I think this object knows you.'];function blueyPick40(items,index){return items[index%items.length]}function blueyDynamicObjectReply40(obj){const count=(blueyObjectTapCounts40.get(obj.id)||0)+1;blueyObjectTapCounts40.set(obj.id,count);if(count===1)return `${blueyObjectOpeners40[Math.floor(Math.random()*blueyObjectOpeners40.length)]} ${obj.short}${blueyObjectClosers40[Math.floor(Math.random()*blueyObjectClosers40.length)]}`.replace(/\s+/g,' ').trim();if(count===2&&obj.deeper)return `${blueyReturnLines40[Math.floor(Math.random()*blueyReturnLines40.length)]} ${obj.deeper}`.replace(/\s+/g,' ').trim();if(count===3&&obj.rabbit)return obj.rabbit;const play=blueyObjectPlay40[obj.id]||blueyGenericPlay40;if(count>=6&&Math.random()<.12)return `Okay, secret object achievement unlocked: “${obj.title} Enthusiast.” 🏆`;return blueyPick40(play,Math.max(0,count-4))}
inspectBlueyObject=function(obj,el){blueyStopDepthFlight();blueyStageActivity({front:true});blueyObjectFocus={obj,depth:0};clearTimeout(blueyRoomExpiry);blueyRoomExpiry=setTimeout(()=>{const nodes=[...(blueyVisibleObjects||[])];nodes.forEach(item=>item.classList.add('bluey-object-leaving'));setTimeout(()=>{nodes.forEach(item=>item.remove());blueyVisibleObjects=blueyVisibleObjects.filter(item=>!nodes.includes(item))},420)},42000);window.dispatchEvent(new CustomEvent('bluey:object',{detail:{id:obj.id,name:obj.title}}));let answer=blueyDynamicObjectReply40(obj);const remembered=window.BlueyRelationshipMemory?.callbackFor(obj.id);if(remembered)answer=remembered;setTimeout(()=>{add('assistant',answer);if(typeof blueyVoiceOn==='undefined'||blueyVoiceOn)speak(answer,'curious')},260)};
const blueyRoomInvitationBefore40=blueyRoomInvitation,blueyRoomInvitationCounts40=new Map();blueyRoomInvitation=function(room){const opening={home:'Welcome Home. There is a jar of marbles, my idea lamp, and a little welcome mat on the stage.',quiet:'This is the Quiet Place. I left a slow-falling leaf and a little sand timer here.',edge:'We are at The Edge. I put a tiny light and a marker beside me; I have only explored this far.'}[room];if(!opening)return blueyRoomInvitationBefore40(room);const count=(blueyRoomInvitationCounts40.get(room)||0)+1;blueyRoomInvitationCounts40.set(room,count);const endings=count===1?[' Tap anything that catches your eye.',' I left a few things for you to poke around.',' Pick whatever looks interesting.']:[' You know the room now — explore wherever you like.',' See anything you missed last time?'];return opening+endings[Math.floor(Math.random()*endings.length)]};
(function(){const isMobile=()=>window.matchMedia('(max-width:700px)').matches;const button=document.createElement('button');button.type='button';button.className='bluey-explore-room';button.textContent='Explore room';button.setAttribute('aria-label','Explore Bluey’s room');document.body.appendChild(button);function hasObjects(){return !!document.querySelector('.stage .bluey-interactive-object,.stage .bluey-trip-object')}function collapse(){if(!isMobile())return;document.body.classList.remove('bluey-mobile-stage-exploring');document.body.classList.add('bluey-mobile-stage-collapsed');button.textContent='Explore room';button.setAttribute('aria-expanded','false')}function explore(){if(!isMobile()||!hasObjects())return;document.body.classList.remove('bluey-mobile-stage-collapsed');document.body.classList.add('bluey-mobile-stage-exploring');button.textContent='Back to chat';button.setAttribute('aria-expanded','true')}button.addEventListener('click',()=>document.body.classList.contains('bluey-mobile-stage-exploring')?collapse():explore());document.addEventListener('click',event=>{if(!isMobile()||event.target===button)return;if(event.target.closest('.bluey-interactive-object,.bluey-trip-object'))setTimeout(collapse,80)});window.BlueyMobileStage={explore,collapse}})();
// Release runtime chain V6: capability-gated modules through world artifact memory,
// then the Alpha 47 quiet-home presentation layer.
(function(){
 const MODULE_TIMEOUT=8000;
 function waitFor(ready,done,label){const started=Date.now();(function poll(){if(ready()){done();return}if(Date.now()-started>=MODULE_TIMEOUT){console.error('[Bluey Alpha 47] Capability timeout:',label);done(new Error(label+' capability timeout'));return}setTimeout(poll,40)})()}
 function load(src,attr,ready,next){if(ready()){next&&next();return}let script=document.querySelector(`script[${attr}]`);const advance=()=>waitFor(ready,err=>{if(err)return;next&&next()},src);if(script){advance();return}script=document.createElement('script');script.src=src;script.async=false;script.setAttribute(attr,'1');script.onload=advance;script.onerror=()=>console.error('[Bluey Alpha 47] Failed to load',src);document.body.appendChild(script)}
 load('/alpha41.js','data-bluey-alpha41',()=>!!window.BlueyRelationshipMemory,()=>
 load('/alpha42.js','data-bluey-alpha42',()=>!!window.BlueyObjectContinuity,()=>
 load('/alpha43.js','data-bluey-alpha43',()=>!!window.BlueyWorldStandard,()=>
 load('/alpha44.js','data-bluey-alpha44',()=>!!window.BlueyReleaseCandidate,()=>
 load('/alpha45.js','data-bluey-alpha45',()=>!!window.BlueyRoomIntelligence,()=>
 load('/alpha46.js','data-bluey-alpha46',()=>!!window.BlueyWorldArtifactMemory,()=>
 load('/alpha47-quiet-stage.js','data-bluey-alpha47-quiet',()=>!!window.BlueyQuietStage,()=>{
   if(window.BlueyCharacter)window.BlueyCharacter.version='1.0-alpha47';
   if(window.blueyAbout)window.blueyAbout.version='1.0-alpha47';
   const badge=document.getElementById('bluey-version');if(badge)badge.textContent=window.BLUEY_RUNTIME_VERSION;
   document.title=window.BLUEY_RUNTIME_VERSION;
   window.BlueyAlpha47={version:window.BLUEY_RUNTIME_VERSION,runtimeChain:[41,42,43,44,45,46],presentation:'quiet-home-1.6',brainLab:'2.1',ready:true};
   window.dispatchEvent(new CustomEvent('bluey:alpha47-ready',{detail:window.BlueyAlpha47}));
   console.info('[Bluey Alpha 47] Clean baseline ready: 41 → 46 + quiet home + Brain Lab V2.1');
 })))))))
})();