// Bluey Alpha 43 — Shared World Scene Standard V3
// Every location uses one contract: atmosphere + visible truth + interactive objects + continuity.
(function(){
'use strict';
if(window.BlueyCharacter)window.BlueyCharacter.version='1.0-alpha43.3';
if(window.blueyAbout)window.blueyAbout.version='1.0-alpha43.3';
if(!window.BLUEY_OBJECTS)return;
const obj=(id,icon,title,names,short,deeper,rabbit)=>({id,icon,title,names,short,deeper,rabbit});
const WORLD_STANDARD={
 observatory:{truth:'stars, telescope, star map and Earth window',objects:[obj('observatory-telescope','🔭','Bluey’s telescope',['telescope','scope'],'My telescope. I point it at things that are very far away and then act like I meant to find them.','A telescope gathers more light than our eyes can, letting us see dimmer and more distant objects.','We could point it somewhere interesting next.'),obj('observatory-starmap','✨','The glowing star map',['star map','stars','constellation','map'],'My star map. Basically connect-the-dots with several billion possible dots.','Star maps help identify constellations and locate objects by their position in the sky.','Somewhere on this map is a star with an unnecessarily dramatic name. Probably.'),obj('observatory-earth','🌎','Earth in the big window',['earth','earth window','window','blue marble'],'There she is — the original blue marble. I admit I may be biased.','From far enough away, weather, borders and streets disappear and Earth becomes one bright little world.','It is hard to look at Earth from here and not get at least a little philosophical.'),obj('observatory-planet','🪐','Little planet model',['planet','saturn','planet model'],'I keep a tiny planet around for perspective. Also because rings are excellent accessories.','The planets orbit the Sun at different distances and speeds.','Saturn is absolutely showing off, by the way.')]},
 garage:{truth:'workbench, toolbox, scooter and mystery box',objects:[obj('garage-tools','🧰','Bluey’s toolbox',['toolbox','tools','tool box'],'My toolbox. Half useful things, half things I am convinced will be useful eventually.','A good toolkit grows around the problems you actually solve instead of every tool you might someday need.','There is definitely one screwdriver in here that has achieved seniority.'),obj('garage-scooter','🛴','The little scooter',['scooter','ride'],'My little scooter. Excellent transportation if your destination is approximately over there.','Small machines are fun examples of wheels, bearings, leverage and balance working together.','I have never received a speeding ticket. This may be because I have no license plate.'),obj('garage-box','📦','The mystery box',['box','mystery box','package'],'Ah, the mystery box. I know what is in it. Probably.','Boxes are where projects go while deciding whether they are finished.','Opening it feels like archaeology, except I was the civilization.') ]},
 arcade:{truth:'arcade cabinet, joystick, prize and neon lights',objects:[obj('arcade-cabinet','🕹️','Bluey’s arcade cabinet',['arcade','cabinet','game','machine'],'This one is dangerous. Five minutes can mysteriously become forty-five.','Arcade games are compact feedback loops: action, response, score, retry. That is part of why they are so satisfying.','I am absolutely not blaming the high-score table for anything.'),obj('arcade-prize','🏆','Tiny high-score trophy',['trophy','prize','high score'],'My extremely prestigious tiny trophy. Please hold your applause until the end.','Scores give immediate feedback, but the interesting part is usually what you learn between attempts.','There may have been only one contestant.'),obj('arcade-token','🪙','Lucky arcade token',['token','coin','arcade token'],'My lucky token. Statistically questionable. Emotionally essential.','Physical tokens made each play feel tangible: one coin, one attempt, one little decision.','I keep this one instead of spending it. Terrible business model, great souvenir.')]},
 workshop:{truth:'workbench, blueprint, parts bin and idea prototype',objects:[obj('workshop-bench','🔧','The workbench',['workbench','bench','tools'],'This is where ideas stop being polite little thoughts and start getting sawdust on them.','A workbench is really a thinking surface: lay out the problem, tools, parts and next action where you can see them.','Mine has one rule: unfinished ideas are allowed.'),obj('workshop-blueprint','📐','Bluey’s sketch board',['blueprint','drawing','sketch','plan'],'My sketch board. Some lines are plans. Some are me changing my mind with confidence.','Sketching externalizes an idea so you can inspect, test and change it before investing heavily in it.','The eraser is secretly the most important design tool.'),obj('workshop-prototype','⚙️','The little prototype',['prototype','gear','machine','project'],'This little thing is not finished, which means it still has unlimited potential. Convenient.','Prototypes answer questions cheaply. They do not need to be beautiful; they need to teach you something.','If it rattles, we call that early user feedback.')]}
};
['home','quiet','edge','beach','forest','museum','aquarium'].forEach(r=>WORLD_STANDARD[r]={truth:r+' environment',objects:Array.isArray(BLUEY_OBJECTS[r])?BLUEY_OBJECTS[r]:[]});
Object.entries(WORLD_STANDARD).forEach(([r,c])=>{if(c.objects.length)BLUEY_OBJECTS[r]=c.objects});
function removeScenery(){document.querySelectorAll('.bluey-scenery-43').forEach(n=>n.remove());[...document.body.classList].filter(c=>c.startsWith('bluey-world43-')).forEach(c=>document.body.classList.remove(c))}
function node(cls,html){const n=document.createElement('div');n.className='bluey-scenery-43 '+cls;n.innerHTML=html;return n}
function renderScenery(room){removeScenery();if(!window.blueyStage37)return;document.body.classList.add('bluey-world43-'+room);
 if(room==='observatory'){const stars=node('stars43','');for(let i=0;i<38;i++){const s=document.createElement('i');s.style.left=(3+Math.random()*94)+'%';s.style.top=(5+Math.random()*78)+'%';s.style.animationDelay=(Math.random()*3)+'s';stars.appendChild(s)}blueyStage37.prepend(stars);blueyStage37.append(node('constellation43','✦ ── ✧ ── ✦'));blueyStage37.append(node('earthWindow43','<div>🌎</div>'))}
 if(room==='garage'){blueyStage37.prepend(node('garageWall43','<b>GARAGE</b><span>🔩</span><span>⚙️</span>'));blueyStage37.append(node('bench43','▰▰▰'))}
 if(room==='arcade'){blueyStage37.prepend(node('neon43','<span>ARCADE</span>'));blueyStage37.append(node('pixels43','◆　●　▲　★'))}
 if(room==='workshop'){blueyStage37.prepend(node('workshopWall43','<span>WORKSHOP</span>'));blueyStage37.append(node('peg43','🔩　🔧　⚙️'))}
}
const baseRender=window.renderInteractiveObjects;window.renderInteractiveObjects=function(place){const r=baseRender(place);if(Array.isArray(window.blueyVisibleObjects))blueyVisibleObjects.forEach(n=>{if(n&&!n.isConnected&&window.blueyStage37)blueyStage37.appendChild(n)});return r};
const baseEnter=window.enterWorld;window.enterWorld=function(place,announce=true){const r=baseEnter(place,announce);renderScenery(place);window.renderInteractiveObjects?.(place);return r};
const style=document.createElement('style');style.textContent=`.bluey-scenery-43{position:absolute;pointer-events:none;z-index:0}.bluey-world43-observatory .stage{background:linear-gradient(#071426,#102944)!important}.stars43{inset:0}.stars43 i{position:absolute;width:3px;height:3px;border-radius:50%;background:white;box-shadow:0 0 8px #c8e9ff;animation:tw43 2.8s infinite alternate}.constellation43{left:18%;top:28%;color:#dff3ff;font-size:22px}.earthWindow43{right:10%;top:18%;width:100px;height:100px;border:2px solid #8bbbd5;border-radius:50%;display:grid;place-items:center;background:#07121f;font-size:48px}.bluey-world43-garage .stage{background:linear-gradient(#e9edf0,#c9d0d5)!important}.garageWall43{left:6%;top:20%;font-size:18px;color:#52606b}.garageWall43 span{margin-left:20px}.bench43{right:8%;bottom:16%;font-size:35px;color:#795548}.bluey-world43-arcade .stage{background:radial-gradient(circle,#302060,#100d26)!important}.neon43{left:8%;top:18%;font-size:28px;color:#fff;text-shadow:0 0 7px #fff,0 0 16px #7de8ff}.pixels43{right:8%;top:28%;color:#fff;font-size:22px;text-shadow:0 0 10px #fff}.bluey-world43-workshop .stage{background:linear-gradient(#f3ead7,#d8c5a4)!important}.workshopWall43{left:7%;top:19%;font-weight:700;color:#66533d}.peg43{right:8%;top:25%;font-size:25px}.bluey-world43-observatory .greeting,.bluey-world43-arcade .greeting{color:#dff3ff!important}.bluey-world43-observatory .rig,.bluey-world43-garage .rig,.bluey-world43-arcade .rig,.bluey-world43-workshop .rig,.bluey-object{z-index:3}@keyframes tw43{from{opacity:.25}to{opacity:1}}@media(max-width:520px){.earthWindow43{width:64px;height:64px;font-size:30px;right:4%}.constellation43{left:5%;font-size:15px}.garageWall43,.workshopWall43{left:3%;font-size:13px}.pixels43{font-size:15px}}`;document.head.appendChild(style);
const intros={observatory:['Observatory it is. The telescope is out, the star map is glowing, and Earth is showing off in the window again.','Up we go. The Observatory is awake — telescope, star map, Earth window and all.'],garage:['Welcome to the garage. Toolbox is out, scooter is parked, and the mystery box continues to refuse comment.','Garage time. I have tools, a scooter, and one box whose organizational system is best described as “later.”'],arcade:['Arcade! The machines are awake and my tiny trophy is already acting important.','Welcome to the arcade. Neon on, joystick ready, dignity negotiable.'],workshop:['Workshop time. Sketch board, workbench, prototype — this is where unfinished ideas are completely normal.','Welcome to the workshop. Nothing here has to be perfect; it just has to teach us something.']};
function travelRoom(q){for(const r of Object.keys(intros))if(q.includes(r))return r;return null}
const baseSend=window.send;window.send=async function(text){const clean=String(text||'').trim();if(!clean)return;const low=clean.toLowerCase(),room=travelRoom(low);if(room&&/show|take|bring|go|visit|see|room|observatory|garage|arcade|workshop/.test(low)){add('user',clean);history.push({role:'user',content:clean});if(window.input)input.value='';enterWorld(room,false);const a=intros[room][Math.floor(Math.random()*intros[room].length)];setTimeout(()=>{add('assistant',a);history.push({role:'assistant',content:a});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(a,'curious')},320);return}return baseSend(clean)};
window.BlueyWorldStandard={version:'3.0',rooms:WORLD_STANDARD,register(room,config){WORLD_STANDARD[room]=Object.assign({truth:'',objects:[]},config||{});if(WORLD_STANDARD[room].objects?.length)BLUEY_OBJECTS[room]=WORLD_STANDARD[room].objects},enter(room){window.enterWorld?.(room,false)},describe(room){return WORLD_STANDARD[room]||null}};
if(window.blueyWorld)renderScenery(window.blueyWorld);console.info('[Bluey] Alpha 43 Shared World Scene Standard V3 ready');
})();