// Bluey Alpha 47.3 — Atomic World Transition Bridge
// One transition controller owns visual travel. Quiet Home stays blank; discovered rooms can still appear.
(function(){
'use strict';
if(typeof BLUEY_OBJECTS==='undefined'){console.error('[Bluey] World Standard cannot start: BLUEY_OBJECTS unavailable');return}
const obj=(id,icon,title,names,short,deeper,rabbit)=>({id,icon,title,names,short,deeper,rabbit});
const W={
 home:{objects:Array.isArray(BLUEY_OBJECTS.home)?BLUEY_OBJECTS.home:[]},
 library:{objects:Array.isArray(BLUEY_OBJECTS.library)&&BLUEY_OBJECTS.library.length?BLUEY_OBJECTS.library:[obj('library-books','📚','Bluey’s book stack',['books','book stack','bookshelf'],'A few books I keep around for questions that deserve a longer look.','Libraries are basically organized curiosity.','Pick a subject and we can follow it.'),obj('library-lamp','💡','Reading lamp',['lamp','reading lamp'],'My reading lamp. Quiet, useful, and dramatically overqualified for illuminating one page.','Good lighting makes reading easier and keeps the room feeling calm.','Want to pull something off the shelf?')]},
 observatory:{objects:[obj('observatory-telescope','🔭','Bluey’s telescope',['telescope','scope'],'My telescope. I point it at things that are very far away and then act like I meant to find them.','A telescope gathers more light than our eyes can.','We could point it somewhere interesting next.'),obj('observatory-starmap','✨','The glowing star map',['star map','stars','constellation'],'Basically connect-the-dots with several billion possible dots.','Star maps help locate objects in the sky.','Some stars have unnecessarily dramatic names.'),obj('observatory-earth','🌎','Earth in the big window',['earth','window','blue marble'],'There she is — the original blue marble. I may be biased.','From far away Earth becomes one bright little world.','Hard not to get philosophical from up here.')]},
 garage:{objects:Array.isArray(BLUEY_OBJECTS.garage)?BLUEY_OBJECTS.garage:[]},arcade:{objects:Array.isArray(BLUEY_OBJECTS.arcade)?BLUEY_OBJECTS.arcade:[]},workshop:{objects:Array.isArray(BLUEY_OBJECTS.workshop)?BLUEY_OBJECTS.workshop:[]},beach:{objects:Array.isArray(BLUEY_OBJECTS.beach)?BLUEY_OBJECTS.beach:[]},forest:{objects:Array.isArray(BLUEY_OBJECTS.forest)?BLUEY_OBJECTS.forest:[]},museum:{objects:Array.isArray(BLUEY_OBJECTS.museum)?BLUEY_OBJECTS.museum:[]},aquarium:{objects:Array.isArray(BLUEY_OBJECTS.aquarium)?BLUEY_OBJECTS.aquarium:[]},quiet:{objects:Array.isArray(BLUEY_OBJECTS.quiet)?BLUEY_OBJECTS.quiet:[]},edge:{objects:Array.isArray(BLUEY_OBJECTS.edge)?BLUEY_OBJECTS.edge:[]}
};
Object.entries(W).forEach(([r,c])=>{if(c.objects?.length)BLUEY_OBJECTS[r]=c.objects});
const stage=()=>window.blueyStage37||document.querySelector('.stage');
const current=()=>window.BlueyWorldState?.room||document.body.dataset.blueyWorld||window.blueyWorld||'home';
function clearScene(){document.querySelectorAll('.bluey-scenery-43').forEach(n=>n.remove());[...document.body.classList].filter(c=>c.startsWith('bluey-world43-')).forEach(c=>document.body.classList.remove(c))}
function node(cls,html){const x=document.createElement('div');x.className='bluey-scenery-43 '+cls;x.innerHTML=html;return x}
function scene(r){clearScene();const S=stage();if(!S)return false;document.body.classList.add('bluey-world43-'+r);document.body.dataset.blueyWorld=r;S.dataset.blueyWorld=r;S.style.removeProperty('background');if(r==='home'){S.style.setProperty('background','#fff','important');return true}if(r==='observatory'){const x=node('stars43','');for(let i=0;i<34;i++){const q=document.createElement('i');q.style.left=(Math.random()*96)+'%';q.style.top=(Math.random()*80)+'%';x.appendChild(q)}S.prepend(x)}S.append(node('roomLabel43',r.toUpperCase()));return true}
const legacyRender=window.renderInteractiveObjects;
window.renderInteractiveObjects=function(p){const r=legacyRender?.(p);const S=stage();if(Array.isArray(window.blueyVisibleObjects)&&S)blueyVisibleObjects.forEach(x=>{if(x&&!x.isConnected)S.appendChild(x)});requestAnimationFrame(()=>layoutObjects(p));return r};
function layoutObjects(){const S=stage();if(!S)return;const cards=[...S.querySelectorAll('.bluey-interactive-object,.bluey-trip-object,.bluey-object')].filter(x=>x.isConnected);cards.forEach((el,i)=>{el.classList.add('bluey-world-object44');el.style.removeProperty('left');el.style.removeProperty('right');el.style.removeProperty('top');el.style.removeProperty('bottom');el.style.cursor='pointer';el.setAttribute('role','button');if(!el.hasAttribute('tabindex'))el.tabIndex=0;el.dataset.blueyPosition=['left','rightTop','rightBottom','leftBottom'][i%4]})}
const legacyEnter=window.enterWorld;
function paintWorld(p,{objects=false}={}){scene(p);if(objects&&p!=='home')window.renderInteractiveObjects?.(p);layoutObjects();return stage()?.dataset.blueyWorld===p}
function atomicTravel(p,a=true,meta={}){if(!W[p])return false;const from=current();try{legacyEnter?.(p,a)}catch(e){console.warn('[Bluey] legacy enterWorld failed',e)}window.BlueyWorldState={room:p,changedAt:Date.now(),from};try{window.blueyWorld=p}catch(_){};paintWorld(p,{objects:false});requestAnimationFrame(()=>paintWorld(p,{objects:false}));setTimeout(()=>paintWorld(p,{objects:false}),90);window.dispatchEvent(new CustomEvent('bluey:world',{detail:{room:p,from,source:'atomic-world-47.3',requestId:meta.requestId||null,reason:meta.reason||null,suppressGreeting:!!meta.suppressGreeting}}));return true}
window.enterWorld=(p,a=true)=>atomicTravel(p,a,{source:'legacy'});
const css=document.createElement('style');css.textContent=`.bluey-scenery-43{position:absolute;pointer-events:none;z-index:0}.roomLabel43{left:0;right:0;top:18%;text-align:center;font-size:22px;letter-spacing:.08em;opacity:.55}.stars43{inset:0}.stars43 i{position:absolute;width:3px;height:3px;border-radius:50%;background:#fff;box-shadow:0 0 7px #d8f1ff}.stage[data-bluey-world="home"]{background:#fff!important}.stage[data-bluey-world="library"]{background:linear-gradient(#f5efe4,#ddd0bb)!important}.stage[data-bluey-world="observatory"]{background:linear-gradient(#071426,#102944)!important}.stage[data-bluey-world="garage"]{background:linear-gradient(#edf0f1,#c9d0d5)!important}.stage[data-bluey-world="arcade"]{background:radial-gradient(circle,#382169,#100d26)!important}.stage[data-bluey-world="workshop"]{background:linear-gradient(#f4ead5,#d7c39f)!important}.stage[data-bluey-world="beach"]{background:linear-gradient(#bfeaff 0 55%,#f7dfa0 56%)!important}.stage[data-bluey-world="forest"]{background:linear-gradient(#b9ddc2,#477453)!important}.stage[data-bluey-world="museum"]{background:linear-gradient(#eee7da,#c8b89d)!important}.stage[data-bluey-world="aquarium"]{background:linear-gradient(#0d6d91,#06374f)!important}.bluey-world-object44{position:absolute!important;z-index:4!important;pointer-events:auto!important;min-width:86px;max-width:130px;touch-action:manipulation}.bluey-world-object44[data-bluey-position="left"]{left:5%!important;top:54%!important}.bluey-world-object44[data-bluey-position="rightTop"]{right:5%!important;top:43%!important}.bluey-world-object44[data-bluey-position="rightBottom"]{right:7%!important;top:70%!important}.bluey-world-object44[data-bluey-position="leftBottom"]{left:8%!important;top:76%!important}@media(max-width:620px){.roomLabel43{top:10%;font-size:14px}.bluey-world-object44{transform:scale(.86);min-width:78px}}`;document.head.appendChild(css);
const ALIAS={home:'home',house:'home',library:'library',books:'library',office:'workshop',shop:'workshop',lab:'workshop',observatory:'observatory',telescope:'observatory',garage:'garage',arcade:'arcade',workshop:'workshop',beach:'beach',ocean:'beach',forest:'forest',woods:'forest',museum:'museum',aquarium:'aquarium'};
function requestedRoom(q){for(const [a,r] of Object.entries(ALIAS))if(new RegExp('\\b'+a+'\\b').test(q))return r;return null}
function isTravel(q){return /\b(show|take|bring|go|visit|see|travel|head|move|zip|come|return|back|somewhere|let'?s)\b/.test(q)}
function emitAssistant(text){add('assistant',text);history.push({role:'assistant',content:text});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(text,'curious')}
const arrivals={home:'Home. Just me and the white space again. Nice and simple.',library:'Library. Quiet shelves, lots of questions hiding in books.',workshop:'Workshop. This is where unfinished ideas are allowed.',observatory:'Observatory. Stars on, telescope ready.',garage:'Garage. Tools nearby and at least one suspicious box.',arcade:'Arcade. Neon on. Dignity negotiable.',beach:'Beach. The tide can do the moving for a while.',forest:'Forest. Everything gets quieter here.',museum:'Museum. Old things, strange things, and several things I should not touch.',aquarium:'Aquarium. Everybody is swimming except us. Show-offs.'};
const previousSend=window.send;
window.send=async function(t){const c=String(t||'').trim();if(!c)return;const l=c.toLowerCase(),r=requestedRoom(l);if(r&&isTravel(l)){add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';const requestId='travel-'+Date.now();atomicTravel(r,false,{requestId,reason:c,suppressGreeting:true});setTimeout(()=>{if(stage()?.dataset.blueyWorld===r)emitAssistant(arrivals[r]||`Here we are — ${r}.`)},180);return}return previousSend(c)};
window.BlueyWorldStandard={version:'4.7',rooms:W,register(r,c){W[r]=Object.assign({objects:[]},c||{});if(W[r].objects?.length)BLUEY_OBJECTS[r]=W[r].objects},enter:r=>atomicTravel(r,false,{source:'api'}),describe:r=>W[r]||null,current,scene,stage,layoutObjects,transition:atomicTravel,paintWorld,visualReady:r=>stage()?.dataset.blueyWorld===r};
window.BlueyWorldTransition={version:'1.2',travel:atomicTravel,current};
const initial=current();window.BlueyWorldState={room:initial,changedAt:Date.now()};paintWorld(initial,{objects:false});console.info('[Bluey] World Standard V4.7 atomic travel ready');
})();