// Bluey Alpha 44 — Release Candidate QA Guardrails V4
(function(){
'use strict';
if(window.BlueyCharacter)window.BlueyCharacter.version='1.0-alpha44-rc4';if(window.blueyAbout)window.blueyAbout.version='1.0-alpha44-rc4';
const EXPECTED=['home','observatory','garage','arcade','workshop','beach','forest','museum','aquarium','quiet','edge'];
const PRIMARY=['observatory','garage','arcade','workshop','beach','forest','museum','aquarium'];
function rooms(){return window.BlueyWorldStandard?.rooms||{}}
function expectedObjects(room){const cfg=rooms()[room];if(Array.isArray(cfg?.objects))return cfg.objects;return []}
function currentRoom(){return window.BlueyWorldStandard?.current?.()||window.BlueyWorldState?.room||document.body.dataset.blueyWorld||window.blueyWorld||null}
function renderedObjectIds(){return [...document.querySelectorAll('.stage .bluey-interactive-object,.stage .bluey-trip-object,.stage .bluey-object')].map(n=>n.dataset?.objectId||n.dataset?.id||n.getAttribute('data-bluey-object-id')||n.id||'').filter(Boolean)}
function roomClass(room){return document.body.classList.contains('bluey-world43-'+room)}
function report(){const world=window.BlueyWorldStandard,rs=rooms();const c={worldEngine:!!world&&typeof world.enter==='function'&&typeof world.describe==='function',worldVersion:world?.version||'—',relationshipMemory:!!window.BlueyRelationshipMemory,objectContinuity:!!window.BlueyObjectContinuity,mobileStage:!!window.BlueyMobileStage,sendFunction:typeof window.send==='function',enterWorldFunction:typeof window.enterWorld==='function',renderObjectsFunction:typeof window.renderInteractiveObjects==='function',stage:!!window.blueyStage37,missingRooms:EXPECTED.filter(r=>!rs[r]),emptyPrimaryRooms:PRIMARY.filter(r=>expectedObjects(r).length===0),currentWorld:currentRoom(),viewport:`${innerWidth}×${innerHeight}`,touch:'ontouchstart'in window||navigator.maxTouchPoints>0};c.pass=c.worldEngine&&c.relationshipMemory&&c.objectContinuity&&c.sendFunction&&c.enterWorldFunction&&c.renderObjectsFunction&&c.stage&&!c.missingRooms.length&&!c.emptyPrimaryRooms.length;return c}
function smoke(){const r=report();console.group('[Bluey Alpha 44 RC4] smoke test');Object.entries(r).forEach(([k,v])=>console.log(k,v));console.groupEnd();return r}
function worldAudit(){return Object.fromEntries(EXPECTED.map(name=>[name,{objects:expectedObjects(name).map(o=>({id:o.id,title:o.title,names:o.names||[]})),objectCount:expectedObjects(name).length}]))}
async function regressWorlds(){const start=currentRoom()||'home',results=[];for(const room of EXPECTED){try{window.BlueyWorldStandard?.enter(room);await new Promise(r=>setTimeout(r,180));const expected=expectedObjects(room);const expectedIds=expected.map(o=>o.id).filter(Boolean);const state=currentRoom();const theme=roomClass(room)||(room==='home'||room==='quiet'||room==='edge'?document.body.dataset.blueyWorld===room:false);const visible=[...document.querySelectorAll('.stage .bluey-interactive-object,.stage .bluey-trip-object,.stage .bluey-object')].filter(x=>x.isConnected);const ids=renderedObjectIds();const matched=expectedIds.filter(id=>ids.includes(id)).length;const identityObservable=ids.length>0;const objectPass=identityObservable?matched===expectedIds.length:visible.length>=expected.length;const pass=state===room&&theme&&expected.length>0&&objectPass;results.push({room,state,theme,expected:expected.length,visible:visible.length,matched,identityObservable,pass})}catch(e){results.push({room,pass:false,error:String(e)})}}try{window.BlueyWorldStandard?.enter(start)}catch(_){}return results}
function showPanel(){let p=document.getElementById('bluey-rc-panel');if(p){p.remove();return}const r=report();p=document.createElement('div');p.id='bluey-rc-panel';p.innerHTML=`<div class="rc-head"><b>Bluey Alpha 44 RC4</b><button aria-label="Close QA">×</button></div><div class="rc-status ${r.pass?'pass':'fail'}">${r.pass?'CORE PASS — RUN WORLD TEST':'RELEASE BLOCKER'}</div><div>World engine: ${r.worldEngine?'✓':'✗'} (${r.worldVersion}) &nbsp; Memory: ${r.relationshipMemory?'✓':'✗'} &nbsp; Continuity: ${r.objectContinuity?'✓':'✗'}</div><div>Current world: ${r.currentWorld||'—'}</div><div>Rooms missing: ${r.missingRooms.length?r.missingRooms.join(', '):'none'}</div><div>Empty primary rooms: ${r.emptyPrimaryRooms.length?r.emptyPrimaryRooms.join(', '):'none'}</div><div>Viewport: ${r.viewport} &nbsp; Touch: ${r.touch?'yes':'no'}</div><button class="rc-run">Run world regression</button><pre class="rc-results">Ready.</pre>`;document.body.appendChild(p);p.querySelector('.rc-head button').onclick=()=>p.remove();p.querySelector('.rc-run').onclick=async()=>{const out=p.querySelector('.rc-results');out.textContent='Testing worlds…';const results=await regressWorlds();const bad=results.filter(x=>!x.pass);out.textContent=results.map(x=>`${x.pass?'✓':'✗'} ${x.room}: state=${x.state||'-'} | theme=${x.theme?'✓':'✗'} | objects=${x.identityObservable?x.matched:x.visible}/${x.expected}`).join('\n')+`\n\n${bad.length?'BLOCKERS: '+bad.map(x=>x.room).join(', '):'WORLD REGRESSION PASS'}`;const fresh=report();const status=p.querySelector('.rc-status');status.className='rc-status '+(fresh.pass&&!bad.length?'pass':'fail');status.textContent=fresh.pass&&!bad.length?'CORE + WORLD PASS':'RELEASE BLOCKER';const worldLine=[...p.children].find(n=>n.textContent?.startsWith('Current world:'));if(worldLine)worldLine.textContent='Current world: '+(fresh.currentWorld||'—')}}
const style=document.createElement('style');style.textContent=`#bluey-rc-panel{position:fixed;right:12px;bottom:12px;z-index:99999;width:min(440px,calc(100vw - 24px));max-height:72vh;overflow:auto;background:#111b27;color:#eaf6ff;border:1px solid #54718a;border-radius:14px;padding:14px;font:13px/1.45 system-ui;box-shadow:0 10px 40px #0007}#bluey-rc-panel .rc-head{display:flex;justify-content:space-between;align-items:center;font-size:15px;margin-bottom:9px}#bluey-rc-panel button{border:1px solid #69839a;border-radius:9px;background:#203448;color:#fff;padding:7px 10px;cursor:pointer}#bluey-rc-panel .rc-head button{border:0;background:none;font-size:22px;padding:0 4px}.rc-status{font-weight:800;margin:7px 0}.rc-status.pass{color:#8cf0a9}.rc-status.fail{color:#ff9c9c}.rc-run{margin:10px 0}.rc-results{white-space:pre-wrap;background:#0a1119;padding:9px;border-radius:8px;max-height:260px;overflow:auto}@media(max-width:520px){#bluey-rc-panel{right:6px;bottom:6px;width:calc(100vw - 12px);max-height:62vh}}`;document.head.appendChild(style);
window.BlueyReleaseCandidate={version:'44-RC4',report,smoke,worldAudit,regressWorlds,showPanel,featureFreeze:true};
addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='b')showPanel()});if(new URLSearchParams(location.search).get('blueyqa')==='1')setTimeout(showPanel,1200);
setTimeout(()=>{const r=smoke();if(!r.pass)console.warn('[Bluey Alpha 44 RC4] Release blocker detected',r);else console.info('[Bluey Alpha 44 RC4] Core integrity PASS')},1500);
})();