// Bluey Alpha 45 — Room Intelligence V4
// Rooms now remember why Bluey visited, what happened there, and unfinished activities.
(function(){
'use strict';
const WS=()=>window.BlueyWorldStandard;
const state=window.BlueyRoomContext=window.BlueyRoomContext||{room:null,reason:null,reasonText:null,arrivedAt:0,lastObject:null,lastIntent:null,lastTopic:null,turnsHere:0};
state.roomMemories=state.roomMemories||{};
const ROOM_INTEL={workshop:{purpose:'turn ideas into something we can inspect, sketch, build, or test',objects:{idea:['workshop-blueprint','Oh, this belongs in the Workshop. Let me pull the sketch board over. We can give the idea some shape before we make it complicated.'],build:['workshop-prototype','Prototype territory. ⚙️ Let’s make the smallest version that can teach us something.'],stuck:['workshop-bench','Workbench problem. 🔧 Let’s put it down in front of us and break it into smaller pieces.']}},observatory:{purpose:'explore questions, patterns, perspective, and things worth looking at more closely',objects:{explore:['observatory-telescope','Telescope moment. 🔭 Let’s pick something interesting and look closer.'],pattern:['observatory-starmap','The star map feels right for this one. Let’s see what connects to what.'],perspective:['observatory-earth','Come look at Earth with me. Sometimes backing way up changes the question.']}},garage:{purpose:'tinker with practical problems, repairs, and useful tools',objects:{fix:['garage-tools','Toolbox time. 🧰 First let’s figure out what kind of problem we’re actually fixing.'],unknown:['garage-box','Hmm. Mystery-box energy. Let’s open the problem and see what is actually inside.']}},arcade:{purpose:'learn through attempts, feedback, play, and trying again',objects:{practice:['arcade-cabinet','Arcade rules: try it, see what happens, adjust, try again. 🕹️'],goal:['arcade-prize','Before we chase the trophy, let’s decide what winning actually looks like. 🏆']}},beach:{purpose:'slow down, notice things, reset, and explore without needing to accomplish much',objects:{think:['beach-shell','Let’s borrow the seashell for a second. 🐚 What’s the smallest interesting piece of this?'],experiment:['beach-castle','Sandcastle rule: we can build a version that doesn’t have to last forever.'],break:['beach-shell','You said we needed a break, remember? No workbench allowed for a minute. 😄 We can inspect that shell, poke around the sand, or just hang out.']}},forest:{purpose:'notice hidden systems, connections, and gradual growth',objects:{system:['forest-mushroom','This might be a mycelium problem — lots of the important stuff could be happening underneath what we can see.'],growth:['forest-tree','Tree logic: small growth still counts. What’s one branch we can grow next?']}},museum:{purpose:'learn from examples, history, artifacts, and different interpretations',objects:{history:['museum-fossil','Let’s use the fossil approach: what evidence did the earlier version leave behind?'],view:['museum-art','Painting question: is there another way to look at this?']}},aquarium:{purpose:'observe behavior, movement, flow, and systems from another perspective',objects:{flow:['aquarium-fish','Let’s watch the flow instead of one moment. Where does this start, move, and end?'],system:['aquarium-coral','Coral-reef problem: lots of small parts may be supporting the whole thing.']}}};
const KEYWORDS={idea:['idea','design','plan','sketch','imagine'],build:['build','make','create','prototype','toy'],stuck:['stuck','problem','tricky','fix','solve'],explore:['explore','look','see','discover','star','space'],pattern:['pattern','map','connect','relationship'],perspective:['perspective','world','earth','big picture'],fix:['fix','repair','tool','broken'],unknown:['unknown','mystery','not sure'],practice:['practice','learn','try','again','attempt'],goal:['goal','win','score','progress'],think:['think','idea','stuck','wonder'],experiment:['experiment','temporary','test','build'],break:['break','rest','relax','chill','pause','slow down'],system:['system','network','connect','hidden','ecosystem','complex'],growth:['grow','growth','progress','time'],history:['history','before','old','past','example'],view:['interpret','view','meaning','creative'],flow:['flow','move','process','behavior']};
function room(){return WS()?.current?.()||'home'} function objects(r=room()){return WS()?.rooms?.[r]?.objects||[]}
function memory(r=room()){return state.roomMemories[r]||(state.roomMemories[r]={visits:0,lastVisit:0,lastReason:null,lastTopic:null,lastIntent:null,lastObject:null,unfinished:false,summary:null})}
function saveRoom(){const r=state.room||room();if(!ROOM_INTEL[r])return;const m=memory(r);m.lastVisit=Date.now();m.lastReason=state.reason||m.lastReason;m.lastTopic=state.lastTopic||m.lastTopic;m.lastIntent=state.lastIntent||m.lastIntent;m.lastObject=state.lastObject||m.lastObject;m.unfinished=!!(state.lastTopic&&['idea','build','stuck','fix','practice','goal','explore','pattern','system','growth'].includes(state.lastIntent));m.summary=m.lastTopic?`${m.lastIntent||'activity'}: ${m.lastTopic}`:m.summary}
function markObject(id){const S=WS()?.stage?.();if(!S)return;const idx=objects().findIndex(o=>o.id===id),cards=[...S.querySelectorAll('.bluey-interactive-object,.bluey-trip-object,.bluey-object')].filter(x=>x.isConnected),el=cards[idx];if(!el)return;state.lastObject=id;memory().lastObject=id;el.classList.add('bluey-room-suggested');setTimeout(()=>el.classList.remove('bluey-room-suggested'),4200)}
function inferPurpose(text){const q=text.toLowerCase();let best=null,score=0;for(const [intent,words] of Object.entries(KEYWORDS)){const n=words.reduce((a,w)=>a+(q.includes(w)?1:0),0);if(n>score){best=intent;score=n}}return best}
function rememberTopic(text,intent){if(intent)state.lastIntent=intent;const cleaned=text.replace(/\b(can|could|would|please|bluey|let'?s|go|take|show|visit|travel|head|move|zip|come|to|the|a|an|we|i|you|my|your)\b/gi,' ').replace(/\s+/g,' ').trim();if(cleaned.length>4)state.lastTopic=cleaned.slice(0,120);const m=memory();m.lastIntent=state.lastIntent;m.lastTopic=state.lastTopic;m.unfinished=!!state.lastTopic}
function suggestion(text){const r=room(),intel=ROOM_INTEL[r];if(!intel)return null;let intent=inferPurpose(text);const follow=/^(okay|ok|sure|yes|yeah|yep|what about that|keep going|continue|then what|how|why|what next)\b/i.test(text.trim());if(!intent&&follow&&state.lastIntent&&intel.objects[state.lastIntent])intent=state.lastIntent;if(state.room===r&&state.reason&&intel.objects[state.reason]&&/\b(what should we do|what can we do|what now|what do you want to do|why did we come here)\b/i.test(text))intent=state.reason;const data=intel.objects[intent];return data?{intent,objectId:data[0],response:data[1]}:null}
function contextualFollow(text){const r=room(),q=text.toLowerCase(),intel=ROOM_INTEL[r],m=memory(r);if(!intel)return null;if(/\b(what were we doing|where were we|what was i doing|what did we do here|remember what we were doing)\b/.test(q)&&m.lastTopic)return {objectId:m.lastObject,response:`Yep. Last time we were here, we were working on ${m.lastTopic}. ${m.unfinished?'We left that thread open, so we can pick it right back up.':'I remember it.'}`};if(/\b(pick it back up|continue where we left off|back to it|resume)\b/.test(q)&&m.lastTopic)return {objectId:m.lastObject,response:`I remember. We left off with ${m.lastTopic}. Let’s pick up from there instead of starting over.`};if(state.reason==='break'&&r==='beach'){if(/\b(work|build|fix|project|email|code)\b/.test(q))return {objectId:'beach-shell',response:'Hey, that sounds suspiciously like work. 😄 We came here for a break. We can absolutely go back to it when you’re ready—or stay here another minute and investigate that shell.'};if(/\b(what should we do|what now|anything|bored|idea)\b/.test(q))return {objectId:'beach-shell',response:'We came here to take a break, so I vote for something gloriously unnecessary. 😄 Shell inspection, sandcastle engineering with zero deadlines, or we can just listen to the imaginary waves.'}}if(r==='workshop'&&state.lastIntent==='build'&&/\b(how|next|continue|then|what next)\b/.test(q))return {objectId:'workshop-prototype',response:`Let’s keep it on the prototype table. ${state.lastTopic?`For ${state.lastTopic}, `:''}we only need the next testable piece—not the perfect finished version.`};if(r==='observatory'&&state.lastIntent&&/\b(closer|more|continue|what else|next)\b/.test(q))return {objectId:state.lastObject||'observatory-telescope',response:'Let’s stay with it. Instead of jumping to a new answer, we can change the zoom: closer for details, farther out for the pattern.'};return null}
function roomHelp(){const r=room(),intel=ROOM_INTEL[r],m=memory(r);if(!intel)return null;if(state.room===r&&state.reason){const x=intel.objects[state.reason];if(x)return x[1]}if(m.visits>1&&m.unfinished&&m.lastTopic)return `We’ve been here before. Last time we left ${m.lastTopic} sitting here for us. We can pick that back up, or do something completely different.`;const names=objects(r).map(o=>o.title).join(', '),flavor={workshop:'This is where ideas are allowed to get messy in a good way. 😄',observatory:'This is where we zoom in, zoom out, and follow interesting questions.',beach:'This is where we can lower the productivity setting for a minute. 😄',forest:'This is a good place for noticing things that connect quietly.',museum:'This is where old clues and different viewpoints get useful.',aquarium:'This is where watching the flow can tell us more than staring at one moment.',garage:'This is where practical problems meet suspicious quantities of tools.',arcade:'This is where trying again is part of the game.'}[r]||'';return `${flavor} We can ${intel.purpose}.${names?` Around us: ${names}.`:''}`}
function rememberTravel(detail){saveRoom();const r=detail?.room||room(),m=memory(r);state.room=r;state.arrivedAt=Date.now();state.turnsHere=0;state.lastObject=m.lastObject||null;state.lastIntent=m.lastIntent||null;state.lastTopic=m.lastTopic||null;m.visits++;const pending=window.BlueyPendingTravelReason;if(pending){state.reason=pending.reason;state.reasonText=pending.text;m.lastReason=pending.reason;window.BlueyPendingTravelReason=null}else{state.reason=null;state.reasonText=null}}
window.addEventListener('bluey:world',e=>rememberTravel(e.detail));
function captureTravelReason(text){const q=text.toLowerCase(),target=Object.entries({workshop:['workshop','office','shop','lab'],observatory:['observatory'],garage:['garage'],arcade:['arcade'],beach:['beach','ocean'],forest:['forest','woods'],museum:['museum'],aquarium:['aquarium']}).find(([,names])=>names.some(n=>new RegExp('\\b'+n+'\\b').test(q)));if(!target)return;const travel=/\b(go|take|show|visit|travel|head|move|zip|come|return|back)\b/.test(q);if(!travel)return;saveRoom();window.BlueyPendingTravelReason={room:target[0],reason:inferPurpose(text),text,topic:state.lastTopic}}
const previousSend=window.send;window.send=async function(t){const c=String(t||'').trim();if(!c)return;const l=c.toLowerCase();captureTravelReason(c);state.turnsHere=(state.turnsHere||0)+1;const follow=contextualFollow(c);if(follow&&!/\b(go|take|show|visit|travel|room|office)\b/.test(l)){add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';if(follow.objectId)markObject(follow.objectId);setTimeout(()=>{add('assistant',follow.response);history.push({role:'assistant',content:follow.response});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(follow.response,'curious')},180);return}if(/\b(what can we do here|what do we do here|why are we here|what is this room for|what's this room for|what should we do|what now)\b/.test(l)){add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';const a=roomHelp();if(a){const s=suggestion(c);if(s)markObject(s.objectId);setTimeout(()=>{add('assistant',a);history.push({role:'assistant',content:a});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(a,'curious')},180);return}}const s=suggestion(c);if(s&&!/\b(go|take|show|visit|travel|room|office|beach|garage|museum|aquarium|forest|arcade|observatory)\b/.test(l)){rememberTopic(c,s.intent);add('user',c);history.push({role:'user',content:c});if(window.input)input.value='';markObject(s.objectId);setTimeout(()=>{add('assistant',s.response);history.push({role:'assistant',content:s.response});if(typeof speak==='function'&&(typeof blueyVoiceOn==='undefined'||blueyVoiceOn))speak(s.response,'curious')},180);return}const inferred=inferPurpose(c);if(inferred)rememberTopic(c,inferred);return previousSend(c)};
const css=document.createElement('style');css.textContent=`.bluey-room-suggested{animation:blueyRoomNudge 1.15s ease-in-out 3!important;box-shadow:0 0 0 4px rgba(28,174,232,.22),0 8px 28px rgba(15,126,180,.25)!important}@keyframes blueyRoomNudge{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-7px) scale(1.04)}}@media(prefers-reduced-motion:reduce){.bluey-room-suggested{animation:none!important;outline:4px solid rgba(28,174,232,.3)}}`;document.head.appendChild(css);
state.room=room();memory(state.room).visits=Math.max(1,memory(state.room).visits);
window.BlueyRoomIntelligence={version:'4.0',rooms:ROOM_INTEL,state,suggestion,roomHelp,markObject,inferPurpose,contextualFollow,memory,saveRoom};
console.info('[Bluey] Alpha 45 Room Intelligence V4 ready');
})();