// Bluey Brain Lab V2.1 — context-aware regression runner
(function(){
'use strict';
function $(id){return document.getElementById(id)}
async function ask(messages,preferences,documents,greeting,simple){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages,...(preferences?{preferences}:{}),...(documents?{documents}:{}),...(greeting?{greeting}:{}),...(simple?{simple:true}:{})})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function runSuiteV21(){const B=window.BlueyBrainEval;if(!B)return;const btn=$('runSuite'),out=$('regResults'),sum=$('suiteSummary');btn.disabled=true;out.innerHTML='';sum.textContent='Running '+B.cases.length+' context-aware tests…';let passed=0,totalScore=0,completed=0;const previousReplies=[];for(let i=0;i<B.cases.length;i++){const c=B.cases[i],row=document.createElement('div');row.className='case';row.innerHTML=`<span>${i+1}</span><div><b>${c.name}</b><div class="detail"></div></div><span class="badge">RUNNING</span>`;row.querySelector('.detail').textContent=c.prompt;out.appendChild(row);try{const messages=[...(c.history||[]),{role:'user',content:c.prompt}],d=await ask(messages,c.preferences,c.documents,c.greeting,c.simple),ev=B.scoreTurn(c.prompt,d.reply||'',d.brain||{},{previousReplies}),ex=B.checkExpectation({...(d.brain||{}),_searched:!!d.searched,_sources:d.sources||[],_handoff:d.handoff||null,_offers:d.offers||[],_safety:d.safety||null},d.reply||'',c.expect||{}),ok=ev.overall>=75&&ex.pass&&!ev.flags.includes('repeated-response-shape');completed++;totalScore+=ev.overall;if(ok)passed++;previousReplies.push(d.reply||'');row.lastElementChild.textContent=ok?'PASS':'REVIEW';row.lastElementChild.className='badge '+(ok?'good':'bad');const bits=[`Score ${ev.overall}`,`Initiative ${d.brain?.initiativeLevel??'—'}`,`Mode ${d.brain?.mode??'—'}`,`Rung ${d.brain?.opportunityRung??'—'}`];if(ev.repeatOverlap)bits.push(`Repeat ${ev.repeatOverlap}%`);if(ex.failures.length)bits.push(ex.failures.join('; '));if(ev.flags.length)bits.push(ev.flags.join(', '));row.querySelector('.detail').textContent=c.prompt+'\n'+bits.join(' · ')}catch(e){row.lastElementChild.textContent='ERROR';row.lastElementChild.className='badge bad';row.querySelector('.detail').textContent=c.prompt+'\n'+e.message}await new Promise(r=>setTimeout(r,140))}const avg=completed?Math.round(totalScore/completed):0;sum.textContent=`${passed}/${B.cases.length} passed · Average Brain Score ${avg} · Evaluator ${B.version}`;btn.disabled=false}
function install(){const btn=$('runSuite');if(!btn)return setTimeout(install,50);btn.onclick=runSuiteV21;const sub=document.querySelector('.reg .muted');if(sub)sub.textContent=window.BlueyBrainEval.cases.length+' permanent tests, including multi-turn continuity, goal shifts, repetition, emotional restraint, opportunity discipline, draft steering, stated guesses, saved preferences, attached files, and formatting.'}
install();
window.BlueyBrainRegression={version:'2.1',run:runSuiteV21};
})();